#!/bin/bash
if [ -z "$1" ]; then
   echo usage: $0 \"comets script name\"
   exit
fi
SCRIPT=$1

VERSION=comets_2.5.8


java -classpath  $GUROBI_HOME/linux64/lib/gurobi.jar:$COMETS_HOME/lib/junit/junit-4.12.jar:$COMETS_HOME/junit/hamcrest-core-1.3.jar:$COMETS_HOME/lib/jogl/jogamp-all-platforms/jar/jogl-all.jar:$COMETS_HOME/lib/jogl/jogamp-all-platforms/jar/gluegen-rt.jar:$COMETS_HOME/lib/jogl/jogamp-all-platforms/jar/gluegen.jar:$COMETS_HOME/lib/jogl/jogamp-all-platforms/jar/gluegen-rt-natives-linux-amd64.jar:$COMETS_HOME/lib/jogl/jogamp-all-platforms/jar/jogl-all-natives-linux-amd64.jar:$COMETS_HOME/lib/JMatIO/lib/jamtio.jar:$COMETS_HOME/lib//JMatIO/JMatIO-041212/lib/jmat.jar:$COMETS_HOME/bin/$VERSION.jar -Djava.library.path=/usr/local/lib/jni:$GUROBI_HOME/linux64/lib  edu.bu.segrelab.comets.Comets -loader edu.bu.segrelab.comets.fba.FBACometsLoader -script $SCRIPT
